apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: snap-import-api
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/PROJECT/apps/snap-import:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: prod
